### ISSUE TITLE
Scraper for Earl Blumenauer

### ISSUE THREAD

**Issue by dwillis** [TheUpshot/statement#67]
http://blumenauer.house.gov/index.php?option=com_content&view=category&id=63&Itemid=220

**Comment by chriszs** [comment]
Hidden (non-broken) RSS, may be usable: http://blumenauer.house.gov/index.php?option=com_content&view=category&id=63&Itemid=220&format=feed&type=rss

**Comment by dwillis** [comment]
great find, thanks!
