### ISSUE TITLE
Combine scrapers for Drupal sites into one?

### ISSUE THREAD

**Issue by mickaobrien** [TheUpshot/statement#77]
When adding the scraper for Tim Walz (#76) I noticed that several other sites are structured the same way. It looks they're all Drupal sites, maybe using the same plugin.

These sites (which are already scraped):
- http://sherman.house.gov/media-center,
- http://mccaul.house.gov/media-center,
- https://ellison.house.gov/media-center,
- http://mcnerney.house.gov/media-center,
- http://sanford.house.gov/media-center,
- http://butterfield.house.gov/media-center,
- http://walz.house.gov/media-center,

and these (which aren't):
- http://quigley.house.gov/media-center, #53
- https://pingree.house.gov/media-center/press-releases, #54
- http://sarbanes.house.gov/media-center/press-releases, #57
- http://butterfield.house.gov/media-center/press-releases, #58
- http://wilson.house.gov/media-center/press-releases, #59
- https://bilirakis.house.gov/press-releases, #69

can all be scraped by using something like this:

```ruby
def scrape(url)
    doc = open_html(url)

    source = ...
    domain = ...

    doc.css("#region-content .views-row").each do |row|
        title_anchor = row.css("h3 a")
        title = title_anchor.text
        release_url = "http://#{domain + title_anchor.attr('href')}"
        raw_date = row.css(".views-field-created").text
        results << { :source => source_url, :url => release_url, :title => title, :date => Date.parse(raw_date), :domain => domain }
    end
    results
end
```

Would it be worth combining them into one scraper?

**Comment by dwillis** [comment]
Yeah, it could be, although I've come across congressional sites that have tiny variations that are supremely annoying. But if you're feeling ambitious, I'd certainly welcome it (and if not, I'll take a stab myself). I think the method would have a canned list of domains & urls but would be great if it also accepted arbitrary lists, too.

**Comment by mickaobrien** [comment]
Yeah, I'm sure there'll be plenty of sites where it should work but won't! But I'm happy to have a go at it.
