### ISSUE TITLE
Twitter::Client#user_timeline no method error

### ISSUE THREAD

**Issue by wismer** [TheUpshot/statement#82]
I'm not sure if this is a bug or I'm configuring it wrong, but `Statement::Tweets#timeline` calls `Twitter::Client#user_timeline`. Should it be responding to the twitter REST client instead? I've never used the streaming API before so maybe it's related to that but I am unsure.

```ruby
t = Statement::Tweets.new
t.timeline("Robert_Aderholt")
# => NoMethodError: undefined method `user_timeline' for #<Twitter::Client:0x007fe6340f13e8>


# in Twitter::Client
a.client.user_timeline 
# => NoMethodError: undefined method `user_timeline' for #<Twitter::Client:0x007fe6340f13e8>
```

**Comment by dwillis** [comment]
You are correct: It should be calling `rest_client` instead.
